### ISSUE TITLE
xf86-video-fbturbo

### ISSUE THREAD

**Issue by streamnsight** [mripard/xf86-video-armsoc#3]
How is this related to:

https://github.com/ssvb/xf86-video-fbturbo

?

Do I need both?

**Comment by mripard** [comment]
> How is this related to: https://github.com/ssvb/xf86-video-fbturbo?

It's not related.

> Do i need both?

I don't know, to do what?

**Comment by streamnsight** [comment]
to build a video driver for CHIP

**Comment by mripard** [comment]
The display driver is in the kernel. This is needed if you want to use the display driver and the GPU. However, there's no public OpenGL implementation yet, so this is going to be useless anyway.
